name: pipeline

on:
  push:
    branches:
      - main

jobs:
  first-build:
    runs-on: ubuntu-latest

    steps:
      - name: print echo
        run: echo "Hello from my pipeline"

      - name: display date
        run: date





































